<a href="https://colab.research.google.com/github/Komilovv/Python-Tasks/blob/main/Tasks_to_pass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.

In [ ]:
np.__version__
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

In [ ]:
list = [54564,45,44564,-487]
list_arr = np.array(list)
list_arr

array([54564,    45, 44564,  -487])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



In [ ]:
zero_9 = np.zeros(9)
zero_9

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



In [ ]:
arr1 = np.array(['Hidoyat','Najot','Mag`firat','Saodat','Muhabbat','Sakinat','Ilm','Nusrat','Rahmat','Darojat',100,99,63])
arr1_size = arr1.nbytes
arr1_size

1092

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



In [ ]:
arr2 = np.zeros(12)
arr2[5] = 1
arr2

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



In [ ]:
vec = np.arange(20,59)
vec

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



In [ ]:
vec1 = np.array([78,5168,4457,-873])
vec1_rev = np.flip(vec1)
vec1_rev

array([-873, 4457, 5168,   78])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


In [ ]:
mat = np.arange(12,21).reshape(3,3)
mat

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





In [ ]:
arr3 = np.array([3, 7, 0, 0, 9, 0])
print(np.nonzero(arr3))

(array([0, 1, 4]),)


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


In [ ]:
arr4 = np.random.random(8)
arr4.reshape(2,2,2)

array([[[0.14037144, 0.4362253 ],
        [0.10919312, 0.05189093]],

       [[0.86488251, 0.57648135],
        [0.36571727, 0.22140046]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


In [ ]:
arr5 = np.random.randn(9,9)
print(np.max(arr5),'\n',np.min(arr5))

1.9472667985808025 
 -2.042912818442727


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



In [ ]:
mat1 = np.random.randn(6,3)
mat2 = np.random.randn(3,4)
print(np.dot(mat1,mat2))

[[-1.96817927  0.45566796  0.96163834 -1.76868377]
 [ 0.74181554 -1.58228458 -1.13696423 -1.94626734]
 [ 1.4435409  -0.67474183 -1.42674905  0.28460471]
 [ 1.05911313 -0.54940566 -1.02994069  0.14148698]
 [ 0.66571129 -0.41051569 -0.20405918  0.3104504 ]
 [-2.44892185  0.51402912  1.01568964 -2.40718245]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
x = np.array([12,548,18469,1,-1999])
y = np.array([-12,548,18469,898,472])
print(x > y, x < y, x <= y, x >= y)


[ True False False False False] [False False False  True  True] [False  True  True  True  True] [ True  True  True False False]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-68-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-68-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-68-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


In [ ]:
mass = np.arange(8,127,3)
mass1 = np.arange(4,99,2)
print(np.intersect1d(mass,mass1))

[ 8 14 20 26 32 38 44 50 56 62 68 74 80 86 92 98]


#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

%, np.floor, astype, np.trunc


In [ ]:
mas = np.random.randn(10)


In [ ]:
mas_int = (mas - mas%1)
mas_pos = mas_int[mas_int > 0]
mas_pos

array([1., 2., 1.])

In [ ]:
mas_int1 = np.floor(mas)
mas_pos1 = mas_int1[mas_int1 >0]
mas_pos1


array([1., 2., 1.])

In [ ]:
mas_int2 = mas.astype(int)
mas_pos2 = mas_int2[mas_int2>0]
mas_pos2

array([1, 2, 1])

In [ ]:
mas_int3 = np.trunc(mas)
mas_pos3 = mas_int3[mas_int3 >0]
mas_pos3

array([1., 2., 1.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



In [ ]:
mat = np.arange(9).reshape(3,3)% 3
mat        # To'g'risi GPT o'rgatdi

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



In [ ]:
vec2 = np.random.randint(10,size=(5))
s_vec2 = np.sort(vec2)
s_vec2

array([3, 4, 4, 5, 9])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

In [ ]:
x = np.random.randn(2,3)
y = np.random.randn(2,3)
print(x==y)
print(np.equal(x,y))

[[False False False]
 [False False False]]
[[False False False]
 [False False False]]


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


In [ ]:
a = np.random.randn(6,3)
b = np.random.randn(3,4)
axb = np.dot(a,b)
axb

array([[ 0.02260383,  0.66471645,  0.02863   ,  0.2390288 ],
       [-1.81344779, -0.87835058,  2.90501729, -4.74879734],
       [-1.77773096, -1.60639623, -0.57647163, -2.65374574],
       [-0.71075428, -0.1604247 ,  1.82824197, -2.25285946],
       [-1.50968208, -1.7627585 , -0.29589359, -2.51682738],
       [-0.90805572, -1.46051428, -0.33642883, -1.54572364]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


In [ ]:
vec3 = np.random.randn(5)
vec3

array([ 0.36654613,  0.10347911, -0.99381147, -2.48261819, -1.52542219])

In [ ]:
sd=vec3.argmax()
vec3[sd] = 0
vec3

array([ 0.        ,  0.10347911, -0.99381147, -2.48261819, -1.52542219])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


In [ ]:
today = np.datetime64('today')
yesterday = today-1
tomorrow = today+1
print("Bugun:",  today,'\n',
      "Kecha:",  yesterday,'\n',
      "Erta:",  tomorrow)

Bugun: 2024-06-06 
 Kecha: 2024-06-05 
 Erta: 2024-06-07


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.
`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
s_date = np.datetime64("2016-01-01")
e_date = np.datetime64("2016-02-01")
all = np.arange(s_date,e_date)
all

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


In [ ]:
# 19 - savol bilan bir xil

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


In [ ]:
a = np.random.randn(19)
b = np.random.randn(19)
c = np.random.randn(19)
sum = np.add(a,b,c)
sum

array([ 0.74915581,  0.76075489,  1.60772165,  0.18934805, -0.2316136 ,
       -1.98707034,  0.59426874,  1.07928514, -1.09040968, -0.5199641 ,
        1.45537423, -1.29945354, -0.64802298,  0.91035904, -0.23917983,
        0.01985563,  0.23453806, -2.2624846 ,  1.09706341])

In [ ]:
np.add.reduce(a)


-2.0178205783801664

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.
`💡Ishora` array[::4]

In [ ]:
import numpy as np

# Asl vektor
vektor = np.array([1, 2, 3, 4, 5])

# Har bir element orasiga 3 ta nol qo'shish uchun yangi vektor yaratamiz
yangi_vektor = np.zeros(len(vektor) * 4 - 3, dtype=int)  # (len(vektor) - 1) * (1 + 3) + 1
yangi_vektor[::4] = vektor

print(yangi_vektor)
#The code had been written by GPT

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
`💡Ishora` stride_tricks.as_strided

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
itemsize = a.strides[0]
itemsize
b = np.lib.stride_tricks.as_strided(a,shape=(11,4),strides=(8,8))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


In [ ]:
import numpy as np
# Author is GPT
# Ixtiyoriy sonlardan tashkil topgan massiv yaratish
a = np.array([3, 1, 2, 3, 4, 2, 5, 3, 2, 5, 2, 4, 1, 3, 4, 5, 3])

# Har bir qiymatning chastotasini hisoblash
counts = np.bincount(a)

# Eng ko'p uchraydigan qiymatni topish
most_frequent_value = np.argmax(counts)

print("Massiv:", a)
print("Har bir qiymatning chastotasi:", counts)
print("Eng ko'p uchraydigan qiymat:", most_frequent_value)


Massiv: [3 1 2 3 4 2 5 3 2 5 2 4 1 3 4 5 3]
Har bir qiymatning chastotasi: [0 2 4 5 3 3]
Eng ko'p uchraydigan qiymat: 3
